stages:
  - build

docker build_devel:
  stage: build
  only:
  - xacc-devel
  script:
  - cd docker/ci/ubuntu1804/devel && docker build -t xacc/devel-ci . --no-cache

docker build_master:
  stage: build
  only:
  - master
  script:
  - cd docker/ci/ubuntu1804/master && docker build -t xacc/master-ci . --no-cache

macosx build_master:
  stage: build
  only:
  - master
  tags:
  - osx
  script:
  - mkdir build && cd build && cmake .. -DXACC_BUILD_TESTS=TRUE && make -j$(sysctl -n hw.physicalcpu) install && ctest --output-on-failure 

