stages:
  - build
  - deploy

docker build_devel:
  stage: build
  except:
  - schedules
  only:
  - xacc-devel
  script:
  - cd docker/ci/ubuntu1804/devel && docker build -t xacc/devel-ci . --no-cache

docker build_master:
  stage: build
  except:
  - schedules
  only:
  - master
  script:
  - cd docker/ci/ubuntu1804/master && docker build -t xacc/master-ci . --no-cache
  - git remote add -t master aideqc https://amccaskey:$GITHUB_ACCESS_TOKEN@github.com/aide-qc/xacc
  - git push -f aideqc HEAD:master

docker run_docker_deploy:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/deploy/dev && docker build -t xacc/xacc . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u xacc --password-stdin
  - docker push xacc/xacc

docker run_docker_xacc_quac_deploy:
  stage: deploy
  only: 
   - schedules
  script:
  - cd docker/deploy/dev_quac && docker build -t xacc/xacc-quac . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u xacc --password-stdin
  - docker push xacc/xacc-quac

docker run_docker_xacc_qcs_deploy:
  stage: deploy
  only: 
   - schedules
  script:
  - cd docker/deploy/dev_qcs && docker build -t xacc/xacc-qcs . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u xacc --password-stdin
  - docker push xacc/xacc-qcs
